### PR TITLE
New Playerctl Signal Module

### PR DESCRIPTION
**Pull request by JavaCafe01**
This is a signal module in which users can connect to signals to grab playerctl info. Currently, this is what it supports:

- Song Title
- Album Art (the path this module downloaded the art to)
- If playing or not
- Position
- Song Length

This module relies on `playerctl` and `curl`. If the user has this module disabled, they won't need those programs.

- [x] the actual daemon
- [x] use `-F` (follow) to get rid of the time stuff (update when change)
- [x] documentation/examples

Using this module, one can make a widget for a playerctl app such as ncspot and not worry about the backend:

image

Any more ideas and feature requests are welcome!

### CODE REVIEW

**Comment by JavaCafe01** [comment]
@Nooo37 On my system `$XDG_CACHE_HOME` isn't set, so it defaults to `$HOME/.cache/awesome`. The code here should switch to the `.cache` folder if the XDG variable isn't set,. If yours is, can you try the script out? My shell scripting sucks.

**Comment by Nooo37** [comment]
Looks good and works for me with mpd except for the album art which seems to be implemented spotify-specific. There are only two little rather unrelated things: The comment at the start needs to be renewed. `bling::playerctl::info` is apperently `bling::playerctl::position` and the variable names `stdout` and `out` are also a little untelling. The folder name should maybe also be `signal` since except for `helpers` and `icons` the other three folders (and the two that are actually called by the user) are also in singular. Good job though

**Comment by JavaCafe01** [comment]
@Nooo37 Alright I'll get that done, I know the album art is spotify specific (but somehow it works for youtube thumbnails). I can implement an option or a detection to switch between the commands.

**Review by Nooo37 — APPROVED** [review]
Looks good :+1:

**Pull request merged**
